name: EasyHub
author: JusztPandaa
main: Hub\Hub
api: [3.0.0]
version: 1.0
description: "a /hub plugin for pocketmine servers"

commands:
  hub:
   description: "Go back to hub"
   permission: hub.cmd
permissions:
  hub.cmd:
    description: "Allows user to run the /hub command"
    default: true
